name: Check for Sensitive Information

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for sensitive information
        run: |
          patterns=(
            "access_key=[A-Za-z0-9_-]+"
            "secret_key=[A-Za-z0-9_-]+"
            "password=[A-Za-z0-9_-]+"
            "private_key=[A-Za-z0-9_-]+"
          )
          for pattern in "${patterns[@]}"
          do
            if git grep -q -E "$pattern" $(git rev-parse --show-toplevel)
            then
              echo "Error: Repository contains sensitive information. Please remove it and try again."
              exit 1
            fi
          done
