name: Check for sensitive data

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TruffleHog
      run: pip install trufflehog

    - name: Scan for sensitive data
      run: trufflehog . --exclude .git

    - name: Fail if sensitive data found
      run: |
        if [ "$?" -eq 0 ]; then
          echo "Error: Sensitive data detected. Please remove it and try again."
          exit 1
        fi
