name: Sensitive Data Check

on:
  pull_request:
    branches:
      - main

jobs:
  scan-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Scan for sensitive data
        run: python scan.py

      - name: Fail if sensitive data found
        run: |
          if [ -f sensitive-data.json ]; then
            echo "::error::Sensitive data found in pull request. Please remove before merging."
            exit 1
          fi
