name: Sensitive Data Check

on:
  push:
    branches: [ main ]

jobs:
  scan-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan for sensitive data
        uses: rlespinasse/github-scan-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_files: '*.png,*.jpg'
          custom_regex: 'my_custom_regex' # Add your own custom regex here

      - name: Fail if sensitive data found
        run: |
          if [ -f sensitive-data.json ]; then
            echo "::error::Sensitive data found in repository."
            exit 1
          fi
