name: Check for sensitive data

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitSecrets
      run: sudo apt-get update && sudo apt-get install git-secrets

    - name: Scan for secrets
      run: git secrets --scan

    - name: Fail if secrets found
      run: |
        if [ "$?" -eq 0 ]; then
          echo "Error: Secrets detected. Please remove them and try again."
          exit 1
        fi
