name: Check for Sensitive Data in Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  check_sensitivity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Sensitive Data
        run: |
          # Define the regex patterns to check for
          patterns=(
            '\b[Pp]assword\b'
            '\b[Ss]ecret[Kk]ey\b'
            '\b[Aa]ccess[Kk]ey\b'
            '\b[Tt]oken\b'
          )

          # Get the list of changed files in the pull request
          changed_files=$(git diff --name-only HEAD..${{ github.event.pull_request.head.sha }})

          # Check each file for the presence of sensitive data
          for file in $changed_files; do
            for pattern in "${patterns[@]}"; do
              if grep -q "$pattern" "$file"; then
                echo "Sensitive data found in file: $file"
                exit 1
              fi
            done
          done
