name: reviewdog
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect-secrets
      uses: reviewdog/action-detect-secrets@master
      with:
        reporter: github-pr-review # Change reporter.
        fail_on_error: true
    - name: Block Commit if Sensitive Data Found
      uses: dessant/lock-threads@v4
      if: always()
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        label-name: 'Sensitive Data Found'
        custom-message: 'Commit blocked: sensitive data detected in changes'

